name: Salesforce Deployment

on:
  pull_request:
    branches: [ qa, sit, uat, prod ]
  push:
    branches: [ qa, sit, uat, prod ]

jobs:
  validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Salesforce CLI + Delta plugin
        run: |
            npm install --global sfdx-cli
            sfdx plugins:install sfdx-git-delta


      - name: Auth to QA Org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL_QA }}" > auth.txt
          sfdx force:auth:sfdxurl:store -f auth.txt -a target

      - name: Generate delta package
        run: |
          sfdx sgd:source:delta --to HEAD --from origin/master --output delta

      - name: Validate delta (check-only)
        run: |
          sfdx force:source:deploy -x delta/package.xml -u target -l RunSpecifiedTests -r "AccountTriggerTest,OpportunityServiceTest" -c -w 30

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Salesforce CLI + Delta plugin
        run: |
          npm install --global sfdx-cli
          sfdx plugins:install sfdx-git-delta

      - name: Auth to QA Org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL_QA }}" > auth.txt
          sfdx force:auth:sfdxurl:store -f auth.txt -a target

      - name: Generate delta package
        run: |
          sfdx sgd:source:delta --to HEAD --from origin/master --output delta

      - name: Deploy delta
        run: |
          sfdx force:source:deploy -x delta/package.xml -u target -l RunSpecifiedTests -r "AccountTriggerTest,OpportunityServiceTest" -w 60
